[run]
deadline = "10m"

[linters]
disable-all = true
enable      = [
  "govet",
  "structcheck",
  "varcheck",
  "typecheck",
  "errcheck",
  "ineffassign",
  "deadcode",
  "gas",
  "unconvert",
  "goconst",
  "gocyclo",
  "gofmt",
  "goimports",
  "prealloc",
  "scopelint",
  "gocritic",
  "staticcheck",
  "unused",
  "gosimple",
  "stylecheck"
]

[linters-settings]
  [linters-settings.errcheck]
  check-blank = true

  [linters-settings.goimports]
  local-prefixes = "github.com/httpway/httpway"

  [linters-settings.gocritic]
  enabled-tags = [
    "diagnostic",
    "style",
    "performance",
    "opinionated"
  ]

[issues]
  [[issues.exclude-rules]]
  path    = ".+_test.go"
  linters = [
    "goconst",
    "scopelint"
  ]