pool:
  vmImage: 'Ubuntu 16.04'

container: pipehub/ci:1

steps:
  - script: |
      go build -mod readonly -o bin/pipehub/pipehub cmd/pipehub/*.go
    displayName: 'Build'

  - script: |
      make go-test
    displayName: 'Quality - Go Test'

  - script: |
      make go-linter
    displayName: 'Quality - Go Linter'

  - script: |
      make go-linter-vendor
    displayName: 'Quality - Go Linter Vendor'

  - script: |
      make docker-linter
    displayName: 'Quality - Docker Linter'
