[run]
deadline = "10m"

[linters]
disable-all = true
enable      = [
  "bodyclose",
  "deadcode",
  "dupl",
  "errcheck",
  "gochecknoglobals",
  "gochecknoinits",
  "goconst",
  "gocritic",
  "gocyclo",
  "gofmt",
  "goimports",
  "golint",
  "gosec",
  "gosimple",
  "govet",
  "lll",
  "ineffassign",
  "maligned",
  "misspell",
  "nakedret",
  "prealloc",
  "scopelint",
  "staticcheck",
  "structcheck",
  "stylecheck",
  "typecheck",
  "unconvert",
  "unparam",
  "unused",
  "varcheck",
  "dogsled",
  "godox",
  "whitespace"
]

[linters-settings]
  [linters-settings.errcheck]
  check-blank = true

  [linters-settings.goimports]
  local-prefixes = "github.com/pipehub/pipehub"

  [linters-settings.gocritic]
  enabled-tags = [
    "diagnostic",
    "style",
    "performance",
    "opinionated"
  ]

  disabled-checks = ["whyNoLint"]

[issues]
  [[issues.exclude-rules]]
  path    = ".+_test.go"
  linters = [
    "goconst",
    "scopelint"
  ]